# beacon/backtest/rules.py
"""
BacktestModifier — optional hooks that alter rebalance behaviour.
"""
from abc import ABC, abstractmethod
from typing import Dict, List, TYPE_CHECKING

import pandas as pd

if TYPE_CHECKING:
    from ..portfolio.base import Portfolio
    from .engine import TradeInstruction


class BacktestModifier(ABC):
    """Abstract base class for modifiers that alter rebalance behaviour.

    A modifier can veto a rebalance entirely via :meth:`should_skip_rebalance`
    or adjust the trade list via :meth:`adjust_trades`.
    """

    @abstractmethod
    def should_skip_rebalance(self,
                              date: pd.Timestamp,
                              portfolio: 'Portfolio',
                              target_weights: Dict[str, float]) -> bool:
        """Return ``True`` to skip the scheduled rebalance on *date*.

        Parameters
        ----------
        date : pd.Timestamp
            The rebalance date.
        portfolio : Portfolio
            Current portfolio state (prices already updated).
        target_weights : dict
            Target weights for this rebalance.

        Returns
        -------
        bool
        """

    @abstractmethod
    def adjust_trades(self,
                      trades: List['TradeInstruction'],
                      date: pd.Timestamp,
                      portfolio: 'Portfolio') -> List['TradeInstruction']:
        """Optionally modify the trade list before execution.

        Parameters
        ----------
        trades : list of TradeInstruction
            The trades generated by :meth:`BacktestEngine._generate_trades`.
        date : pd.Timestamp
            The rebalance date.
        portfolio : Portfolio
            Current portfolio state.

        Returns
        -------
        list of TradeInstruction
            The (possibly modified) trade list.
        """


class DriftThresholdModifier(BacktestModifier):
    """Only rebalance when max weight drift exceeds a threshold.

    Parameters
    ----------
    threshold : float
        Maximum tolerable absolute drift between current and target
        weights. If every asset's drift is within this threshold the
        rebalance is skipped. For example, 0.05 means 5%.
    """

    def __init__(self, threshold: float):
        if threshold < 0:
            raise ValueError("threshold must be non-negative.")
        self.threshold: float = threshold

    def should_skip_rebalance(self,
                              date: pd.Timestamp,
                              portfolio: 'Portfolio',
                              target_weights: Dict[str, float]) -> bool:
        current_weights = portfolio.get_weights()

        # Collect all asset ids from both current and target
        all_assets = set(current_weights.keys()) | set(target_weights.keys())
        if not all_assets:
            return True  # nothing to do

        max_drift = 0.0
        for asset_id in all_assets:
            current_w = current_weights.get(asset_id, 0.0)
            target_w = target_weights.get(asset_id, 0.0)
            drift = abs(current_w - target_w)
            if drift > max_drift:
                max_drift = drift

        skip = max_drift <= self.threshold
        if skip:
            import logging
            logging.getLogger(__name__).debug(
                f"[{date}] Max drift {max_drift:.4f} <= threshold "
                f"{self.threshold:.4f}. Skipping rebalance."
            )
        return skip

    def adjust_trades(self,
                      trades: List['TradeInstruction'],
                      date: pd.Timestamp,
                      portfolio: 'Portfolio') -> List['TradeInstruction']:
        """Pass-through — no trade adjustment."""
        return trades
