# tests/docstyle.py
"""Find public docstrings and docs pages that break the house style.

The Python reference on pybeacon.dev is rendered from docstrings, so a public
docstring is user documentation. It describes what the code does now, in plain
English, with no em-dashes and no internal ticket numbers. History and ticket
references belong in `#` comments beside the code.

Used by tests/test_docs_style.py, and runnable on its own to list every
problem: `python tests/docstyle.py`.
"""
import importlib
import inspect
import pkgutil
import re
import sys
from collections.abc import Iterator
from pathlib import Path

import beacon

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

EM_DASH = "—"
TICKET = re.compile(r"\bBN-\d+")

# Modules that are not part of the public library: command-line entry points,
# and the test helpers' private corners.
SKIPPED_PARTS = ("__main__",)


def public_modules() -> Iterator[str]:
    """Every importable public module under `beacon`."""
    yield "beacon"

    for info in pkgutil.walk_packages(beacon.__path__, "beacon."):
        parts = info.name.split(".")

        if any(part.startswith("_") or part in SKIPPED_PARTS for part in parts):
            continue

        yield info.name


def _members(owner: object,
             module_name: str) -> Iterator[tuple[str, object]]:
    """Public classes and functions defined in *module_name*, and their
    public methods and properties."""
    for name, value in vars(owner).items():
        # `__init__` is rendered too: the reference merges it into its class.
        if name.startswith("_") and not (inspect.isclass(owner)
                                         and name == "__init__"):
            continue

        target = value.fget if isinstance(value, property) else value
        target = getattr(target, "__func__", target)

        if not (inspect.isclass(target) or inspect.isfunction(target)):
            continue

        if getattr(target, "__module__", None) != module_name:
            continue

        yield name, target

        if inspect.isclass(target) and owner is not target:
            for inner, member in _members(target, module_name):
                yield f"{name}.{inner}", member


def docstrings() -> Iterator[tuple[str, str]]:
    """(qualified name, docstring) for every public docstring."""
    for module_name in public_modules():
        try:
            module = importlib.import_module(module_name)
        except ImportError:
            # A module behind an extra that is not installed here.
            continue

        if module.__doc__:
            yield module_name, module.__doc__

        for name, member in _members(module, module_name):
            doc = inspect.getdoc(member) if inspect.isclass(member) else member.__doc__

            if doc and member.__doc__ is not None:
                yield f"{module_name}.{name}", member.__doc__


def page_problems() -> Iterator[str]:
    """Style problems in the docs pages."""
    for page in sorted(DOCS.rglob("*.md")):
        # Generated by scripts/build_gallery.py at build time and not
        # committed; the built-site check in CI covers what it writes.
        if page.name == "gallery.md":
            continue

        text = page.read_text(encoding="utf-8")

        for number, line in enumerate(text.splitlines(), start=1):
            where = f"{page.relative_to(ROOT)}:{number}"

            if EM_DASH in line:
                yield f"{where}: em-dash"

            if TICKET.search(line):
                yield f"{where}: ticket number {TICKET.search(line).group(0)}"


def docstring_problems() -> Iterator[str]:
    """Style problems in public docstrings."""
    for name, doc in docstrings():
        if EM_DASH in doc:
            yield f"{name}: em-dash"

        found = TICKET.search(doc)

        if found:
            yield f"{name}: ticket number {found.group(0)}"


if __name__ == "__main__":
    problems = [*page_problems(), *docstring_problems()]
    print("\n".join(problems))
    print(f"{len(problems)} problem(s)", file=sys.stderr)
