# src/beacon/synthetic/state.py
"""
What a generated store keeps so it can be extended later.

The stored prices say where every name ended up, but not the parameters it was
drawn from: its target volatility, how its variance splits between the market,
its sector and its region, its alpha, its dividend yield. Continuing a name
without those would mean re-estimating them from a few years of one noisy
path, and the extension would behave like a different market. So a generated
store also saves them, in a `synthetic` folder beside the data:

- `settings.json`: the seed, the rates and the calendar it was made with, and
  every extension since.
- `universe.csv.gz`: one row per name, with the parameters above and its
  listed life.

Nothing else reads these files. A store without them loads as normal; it just
cannot be extended.
"""
import gzip
import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

# Inside the store folder.
STATE_DIRECTORY = "synthetic"
SETTINGS_FILE = "settings.json"
UNIVERSE_FILE = "universe.csv.gz"

# Bumped if the saved shape changes in a way an older reader cannot follow.
STATE_VERSION = 1

# The per-name columns an extension needs. Everything else `universe.build`
# produces is either in the reference data already or used only at the start.
UNIVERSE_COLUMNS = ("NAME", "SECTOR", "SUB_INDUSTRY", "REGION", "EXCHANGE",
                    "CURRENCY", "COUNTRY_LISTING", "COUNTRY_DOMICILE",
                    "volatility", "market_share", "sector_share",
                    "region_share", "alpha", "market_cap", "free_float",
                    "dividend_yield", "listed_from", "listed_to")

_DATE_COLUMNS = ("listed_from", "listed_to")


@dataclass
class Settings:
    """How a store was generated, and how far it has been extended.

    Attributes:
        seed: The seed it was generated with. Extensions derive their own
            random streams from it.
        assets: The size of the universe it was generated with. New listings
            are sized against it.
        start: The first date asked for.
        end: The last date asked for, updated by each extension.
        calendar: The exchange whose sessions it has bars on.
        risk_free_rate: Annualised.
        equity_premium: Annualised.
        delisting_rate: Annualised hazard of a name leaving.
        listing_rate: Annualised hazard of a name joining.
        features: Whether it carries features.
        extensions: Each extension, as the first and last new session.
    """
    seed: int
    assets: int
    start: str
    end: str
    calendar: str
    risk_free_rate: float
    equity_premium: float
    delisting_rate: float
    listing_rate: float
    features: bool
    extensions: list[dict[str, str]] = field(default_factory=list)
    version: int = STATE_VERSION


def directory(path: Path) -> Path:
    """Where a store's state lives."""
    return path / STATE_DIRECTORY


def exists(path: Path) -> bool:
    """Whether a store has the state an extension needs."""
    return ((directory(path) / SETTINGS_FILE).is_file()
            and (directory(path) / UNIVERSE_FILE).is_file())


def save(path: Path,
         settings: Settings,
         universe: pd.DataFrame) -> None:
    """Write a store's state beside its data."""
    folder = directory(path)
    folder.mkdir(parents=True, exist_ok=True)

    (folder / SETTINGS_FILE).write_text(
        json.dumps(asdict(settings), indent=2, sort_keys=True) + "\n",
        encoding="utf-8")

    frame = universe.loc[:, list(UNIVERSE_COLUMNS)].copy()

    for column in _DATE_COLUMNS:
        frame[column] = pd.to_datetime(frame[column]).dt.strftime("%Y-%m-%d")

    frame.to_csv(folder / UNIVERSE_FILE, index_label="IDENTIFIER",
                 compression={"method": "gzip", "mtime": 0},
                 lineterminator="\n")


def load(path: Path) -> tuple[Settings, pd.DataFrame]:
    """Read a store's state.

    Raises:
        ValueError: If the store has none, or it was written by a newer
            py-beacon.
    """
    if not exists(path):
        raise ValueError(
            f"{path} cannot be extended: it holds no generator state. Only "
            f"synthetic data generated by py-beacon 0.2.0 or later can be; "
            f"generate a new store instead.")

    payload: dict[str, Any] = json.loads(
        (directory(path) / SETTINGS_FILE).read_text(encoding="utf-8"))

    if payload.get("version", STATE_VERSION) > STATE_VERSION:
        raise ValueError(
            f"{path} was generated by a newer py-beacon; upgrade to extend it.")

    with gzip.open(directory(path) / UNIVERSE_FILE, "rt",
                   encoding="utf-8") as handle:
        universe = pd.read_csv(handle, index_col="IDENTIFIER",
                               keep_default_na=False, na_values=[""])

    for column in _DATE_COLUMNS:
        universe[column] = pd.to_datetime(universe[column])

    return Settings(**payload), universe
