# src/beacon/expressions/stubs.py
"""
Generating a `.pyi` so a static analyser can complete the open namespaces.

`__dir__` (BN-140) is enough for Jupyter and IPython, which ask a live object
what it has. Pylance and mypy do not run code — they read declarations — so
the half of the namespace that is open by design is invisible to them. This
writes that half down.

    python -m beacon.expressions.stubs --out beacon-data.pyi

## Opt-in, and regenerable

The answer depends on what is loaded, so there is no correct file to ship. A
user who wants completions for their own feature datasets generates one; a
user who does not, does not, and everything still works.

## A stale stub is safe, and that ordering is deliberate

A stub kept from an older store will autocomplete a field the data no longer
carries. That is fine, because it then fails validation (`validation.py`) with
a finding naming the field.

The generated file is a **convenience**; the loaded data is the **authority**.
Getting this the other way round — treating the stub as the contract and
validating against it — would let a stale file silently authorise a screen the
data cannot answer, which is precisely the wrong failure: it would select
nothing and say nothing.
"""
import argparse
import logging
import sys
from pathlib import Path

from ..data import store
from ..data.fetcher import DataFetcher
from .namespaces import (
    ACTION_COLUMNS,
    DERIVED_COLUMNS,
    MARKET_COLUMNS,
    REFERENCE_COLUMNS,
)

logger = logging.getLogger(__name__)

HEADER = '''"""Generated by `python -m beacon.expressions.stubs`. Do not edit.

Completions for `beacon.data`, including the feature datasets loaded in the
store this was generated from. Regenerate after loading different data.

A field listed here that the data no longer carries still autocompletes and
then fails validation with a finding: this file is a convenience, and the
loaded data is the authority.
"""
from beacon.expressions.core import Field
'''

# A Python identifier a generated attribute can safely use. A feature field is
# whatever the loader wrote, and a vendor shipping `p/e ratio` or `2024_score`
# would produce a stub that does not parse -- so those are skipped rather than
# mangled into a name that would not resolve anyway.
def _is_identifier(name: str) -> bool:
    return name.isidentifier() and not name.startswith("_")


def _class_name(dataset: str) -> str:
    """A class name for a feature dataset."""
    return "_" + "".join(part.title() for part in dataset.split("_")) + "Fields"


def generate(fetcher: DataFetcher) -> str:
    """The stub source for a loaded store.

    Args:
        fetcher: The data whose feature datasets should complete.

    Returns:
        str: `.pyi` source.
    """
    lines = [HEADER]
    datasets = fetcher.feature_types()

    for dataset in datasets:
        fields = [name for name in fetcher.feature_fields(dataset)
                  if _is_identifier(name)]
        lines.append(_block(_class_name(dataset), fields,
                            f"Fields loaded in the '{dataset}' dataset."))

    lines.append(_features_block(datasets))
    lines.append(_block("_MarketFields",
                        [*MARKET_COLUMNS, *DERIVED_COLUMNS],
                        "Market columns, stored and derived."))
    lines.append(_block("_ReferenceFields", list(REFERENCE_COLUMNS),
                        "Reference dimensions."))
    lines.append(_block("_ActionFields", list(ACTION_COLUMNS),
                        "Corporate action fields."))
    lines.append(_root_block())

    skipped = sum(1 for dataset in datasets
                  for name in fetcher.feature_fields(dataset)
                  if not _is_identifier(name))

    if skipped:
        logger.warning("%d feature field(s) are not valid Python names and "
                       "were left out of the stub; they still resolve at "
                       "runtime through getattr.", skipped)

    return "\n".join(lines)


def _block(class_name: str,
           fields: list[str],
           docstring: str) -> str:
    """One class, one attribute per field."""
    body = [f"class {class_name}:", f'    """{docstring}"""']

    if not fields:
        body.append("    ...")
    else:
        body.extend(f"    {name}: Field" for name in sorted(set(fields)))

    return "\n".join(body) + "\n"


def _features_block(datasets: list[str]) -> str:
    """The features namespace, one attribute per loaded dataset."""
    body = ["class _Features:",
            '    """Feature datasets loaded in this store."""']

    usable = [name for name in datasets if _is_identifier(name)]

    if not usable:
        body.append("    ...")
    else:
        body.extend(f"    {name}: {_class_name(name)}"
                    for name in sorted(usable))

    return "\n".join(body) + "\n"


def _root_block() -> str:
    return ("class _Data:\n"
            '    """The `beacon.data` root."""\n'
            "    market: _MarketFields\n"
            "    reference: _ReferenceFields\n"
            "    actions: _ActionFields\n"
            "    features: _Features\n"
            "\n"
            "data: _Data\n")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m beacon.expressions.stubs",
        description="Generate a .pyi giving static analysers completions for "
                    "the feature datasets in a loaded store.")
    parser.add_argument("--store", type=Path, default=None,
                        help="store directory (default: the one the server "
                             "auto-loads)")
    parser.add_argument("--out", type=Path, default=Path("beacon-data.pyi"),
                        help="where to write (default: beacon-data.pyi)")

    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    path = args.store if args.store is not None else store.default_path()

    try:
        fetcher = store.load(path)
    except Exception as exc:  # reported to the user, not handled
        print(f"error: {exc}", file=sys.stderr)

        return 2

    args.out.write_text(generate(fetcher), encoding="utf-8")

    print(f"Wrote {args.out} from {path} "
          f"({len(fetcher.feature_types())} feature dataset(s)).")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
