# scripts/export_openapi.py
"""
Write the API's OpenAPI specification to a file.

beacon-ui generates its client from this (BU-20), so it is published as a build
artifact on every main build rather than being regenerated by hand and drifting.

The app is built with a throwaway token and no data source. Neither affects the
spec — routes and schemas are declared at import time — and it means the export
needs nothing configured, which is what lets it run as its own CI step without
a fixture.

Usage:

    python scripts/export_openapi.py [output_path]

Defaults to `openapi.json` in the working directory.
"""
import json
import sys
from pathlib import Path

from beacon.server import ServerConfig, create_app

# Any non-empty value satisfies the config; the token never reaches the spec.
EXPORT_TOKEN = "openapi-export"

DEFAULT_OUTPUT = Path("openapi.json")


def export(destination: Path) -> dict[str, object]:
    """Write the spec and return it.

    Args:
        destination: Where to write. Parent directories are created.

    Returns:
        dict: The specification.
    """
    spec = create_app(ServerConfig(auth_token=EXPORT_TOKEN)).openapi()

    destination.parent.mkdir(parents=True, exist_ok=True)

    # Sorted keys and a trailing newline: the file is committed to a client
    # repository and diffed there, and an unstable key order would make every
    # regeneration look like a change.
    destination.write_text(
        json.dumps(spec, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8")

    return dict(spec)


def main() -> int:
    """Export the spec, reporting what was written."""
    destination = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    spec = export(destination)

    paths = len(spec["paths"])  # type: ignore[arg-type]
    schemas = len(spec["components"]["schemas"])  # type: ignore[index]

    print(f"Wrote {destination}: {paths} paths, {schemas} schemas.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
